### ISSUE TITLE
Project Midpoint Checkin

### ISSUE THREAD

**Issue by travis-mann** [Mee42/cs509-project#21]
Todo for project midpoint check-in deliverable

@travis-mann 
- [x] Add updated flightSearch API to frontend
- [x] Fix arrival time data issue: #23
- [x] Update RAD Requirements
- [x] Deploy Application on Free Tier EC2: #26
- [x] Create video recording with OBS/ ShadowPlay / Davinci Resolve
- [x] Submit Video, GitHub Link, Updated RAD

@Mee42 
- [x] Grant admin access to team for this repo
- [x] Update RAD Object Model
- [x] Create Scrum Board for demo: ZenHub or GitHub projects

@ChinhDangg 
- [x] Implement initial version of new flightSearch API based on #20

@Zimaabluee 
- [x] Update RAD Use Case Models
- [x] Add Diagram to Proposed Solution
